### ISSUE TITLE
IoB and Carbs for non loopers

### ISSUE THREAD

**Issue by Foxandxss** [jonfawcett/Nightscout-Tasker-Tizen-Watchface-Integration#1]
Hello friend, good job on this faces, they look fantastic.

I am not a looper (regular libre + miaomiao) but we do track IoB and carbs by entering boluses on xDrip / nightscout.

Can't we have IoB and Carbs as well for non looper profiles? I am sure we can (there are endpoints with the info) but unsure why you only made it work for loopers.

Thanks!

**Comment by jonfawcett** [comment]
@Foxandxss thanks. You should be able to, but I have no way to investigate the json for these to find the correct key names and test the task for anything except Loop. Loop stores most of these details under the key name 'Loop' in the devicestatus json and I don't know if that is a generic looping section or if it is specific for "Loop". So you'll just need to examine your json and see what key names need changed to get the data. The nice thing with autotools json reader is that you can call it by the name without the full path. So just use an online json viewer and find the new names, then edit the tasker json read actions. As long as you keep the tasker global and watchmaker variables the same names, you shouldn't need to edit the face.

If you edit the task to worm, please do a PR with a new file (tasker export xml on the profile) so it can be added for others to use also.

**Comment by Foxandxss** [comment]
Yeah, probably need to hit a different endpoint (e.g /pebble to get IoB) but seems doable.

I will dig when I have a bit of time.
