### ISSUE TITLE
1 step

### ISSUE THREAD

**Issue by mimabud** [jonfawcett/Nightscout-Tasker-Tizen-Watchface-Integration#5]
Hello,
First step doesnt work for me. I am total amateur.  https://[JUST THIS PORTION].herokuapp.com- I dont know how to put it there I tried every option.

**Comment by jonfawcett** [comment]
You take the portion from your nightscout site url that is referenced by the section in brackets and that’s all you enter in that variable. No https:// and no .herokuapp.com
