### ISSUE TITLE
mg to mmol

### ISSUE THREAD

**Issue by Sergio-83** [jonfawcett/Nightscout-Tasker-Tizen-Watchface-Integration#6]
Hi man, can you please tell me how i can change the displayed glucose value mg to mmol on the graph from range 3.5 mmol to 14.0 mmol ? i try do it in watch face "Loop Nightscout Large Time"

sorry for my english, i'm from russia

**Comment by jonfawcett** [comment]
I use Apple now so can only give you some direction based on memory. I think you can either add math /18 within the tasks setting the variables in tasker or you can add math to the variables in watchmaker

**Comment by Sergio-83** [comment]
Thanks for the answer, yesterday I find a solution :)
Tell me which apple is more convenient or better, why did you decide to change it?

![20201108_140236](https://user-images.githubusercontent.com/56828156/98459350-ae861580-21cc-11eb-97c1-e23aa45e3d41.jpg)

This my first watch face :)
