### ISSUE TITLE
Obsolete link

### ISSUE THREAD

**Issue by psonnera** [jonfawcett/Nightscout-Tasker-Tizen-Watchface-Integration#7]
https://github.com/jonfawcett/Nightscout-Tasker-Tizen-Watchface-Integration/wiki/01-Initial-Setup new Nightscout site creation is https://nightscout.github.io/nightscout/new_user/ as nightscout.info is being deprecated

**Comment by jonfawcett** [comment]
Thanks for letting me know. I’ve updated this
